apiVersion: v1
kind: Pod
metadata:
  name: cloudbuilder-deployment
  labels:
    type: jenkins-slave
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cloudbuilder
        image: nginx:1.7.9
        ports:
        - containerPort: 80