apiVersion: v1
kind: Pod
metadata:
  name: cloudbuilder
  labels:
    type: nginx
spec:
  containers:
    - name: test-ramdisk
      image: nginx:1.7.9
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/media/mongo-ramdisk"
        name: mongo-ramdisk
  volumes:
  - name: mongo-ramdisk
    emptyDir: {}