apiVersion: v1
kind: Pod
metadata:
  name: ma-sd-config
spec:
  containers:
  - name: mongo
    image: mongo:3.4.9
    imagePullPolicy: IfNotPresent
    command:
    - "mongod"
    - "--wiredTigerCacheSizeGB"
    - "0.25"
    volumeMounts:
    - mountPath: "/data/db"
      name: mongo-ramdisk
    resources:
      requests:
        memory: "50Mi"
        cpu: "10m"
      limits:
        memory: "50Mi"
        cpu: "10m"
  - name: postgres
    image: postgres:9.5-alpine
    imagePullPolicy: IfNotPresent
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: test_tenant
    resources:
      requests:
        memory: "50Mi"
        cpu: "10m"
      limits:
        memory: "50Mi"
        cpu: "10m"
    volumeMounts:
    - mountPath: "/var/lib/postgresql/data"
      name: postgres-ramdisk
  - name: rabbitmq
    image: rabbitmq:3.6.8-management
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "50Mi"
        cpu: "10m"
      limits:
        memory: "50Mi"
        cpu: "10m"
  volumes:
  - name: mongo-ramdisk
    emptyDir:
      medium: "Memory"
      sizeLimit: 10Mi
  - name: postgres-ramdisk
    emptyDir:
      medium: "Memory"
      sizeLimit: 10Mi